#!/usr/bin/env bash
set -euo pipefail

usage() {
    cat <<'USAGE'
Usage: scripts/build-macos.sh [options]

Build the macOS app from a copy in /private/tmp so Xcode/Make never sees
spaces in the source path.

Options:
  --configuration NAME   Xcode configuration to build (default: Debug)
  --signed               Use normal Apple code signing from Developer.xcconfig
  --unsigned             Disable Apple signing and apply local ad-hoc signing (default)
  --run-swiftlint        Run SwiftLint build phases
  --skip-swiftlint       Skip SwiftLint build phases (default)
  --no-archive           Do not create a zip in build/
  --no-clean             Reuse the temp source copy and DerivedData
  -h, --help             Show this help

Environment overrides:
  AWG_GO_BIN_DIR         Go 1.24+ bin directory (default: first go on PATH)
  AWG_BUILD_TMP_ROOT     Temp build root (default: /private/tmp/awg-apple-build)
  AWG_BUILD_OUTPUT_ROOT  Output root for archives (default: <repo>/build)
  AWG_BUILD_STAMP        Archive timestamp override
  DEVELOPMENT_TEAM       Optional xcodebuild override
  APP_ID_MACOS           Optional xcodebuild override
  APP_ID_IOS             Optional xcodebuild override
  ALLOW_PROVISIONING_UPDATES=1 adds -allowProvisioningUpdates in signed mode
USAGE
}

die() {
    echo "error: $*" >&2
    exit 1
}

require_command() {
    command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

go_version_at_least_1_24() {
    local version="${1#go}"
    local major="${version%%.*}"
    local rest="${version#*.}"
    local minor="${rest%%.*}"

    [[ "$major" =~ ^[0-9]+$ && "$minor" =~ ^[0-9]+$ ]] || return 1
    (( major > 1 || (major == 1 && minor >= 24) ))
}

read_xcconfig_value() {
    local key="$1"
    local file="$2"
    awk -F '=' -v key="$key" '
        $1 ~ "^[[:space:]]*" key "[[:space:]]*$" {
            value = $2
            sub(/^[[:space:]]+/, "", value)
            sub(/[[:space:]]+$/, "", value)
            print value
        }
    ' "$file" | tail -n 1
}

configuration="${CONFIGURATION:-Debug}"
scheme="${SCHEME:-WireGuardmacOS}"
destination="${DESTINATION:-platform=macOS,arch=arm64}"
signing_mode="unsigned"
skip_swiftlint="${SKIP_SWIFTLINT:-1}"
create_archive=1
clean=1

while [[ $# -gt 0 ]]; do
    case "$1" in
        --configuration)
            [[ $# -ge 2 ]] || die "--configuration requires a value"
            configuration="$2"
            shift 2
            ;;
        --signed)
            signing_mode="signed"
            shift
            ;;
        --unsigned)
            signing_mode="unsigned"
            shift
            ;;
        --run-swiftlint)
            skip_swiftlint=0
            shift
            ;;
        --skip-swiftlint)
            skip_swiftlint=1
            shift
            ;;
        --no-archive)
            create_archive=0
            shift
            ;;
        --no-clean)
            clean=0
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            die "unknown option: $1"
            ;;
    esac
done

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
project_root="$(cd "$script_dir/.." && pwd -P)"
tmp_root="${AWG_BUILD_TMP_ROOT:-/private/tmp/awg-apple-build}"
source_copy="$tmp_root/source"
derived_data="$tmp_root/DerivedData"
go_bin_dir="${AWG_GO_BIN_DIR:-}"
go_cache="${GOCACHE:-$tmp_root/go-cache}"
go_mod_cache="${GOMODCACHE:-$tmp_root/go-mod-cache}"
output_root="${AWG_BUILD_OUTPUT_ROOT:-$project_root/build}"

if [[ -z "$go_bin_dir" ]]; then
    require_command go
    go_bin_dir="$(dirname "$(command -v go)")"
fi

[[ -x "$go_bin_dir/go" ]] || die "Go not found at $go_bin_dir/go; set AWG_GO_BIN_DIR"
go_version="$("$go_bin_dir/go" env GOVERSION 2>/dev/null || true)"
[[ -n "$go_version" ]] || go_version="$("$go_bin_dir/go" version | awk '{print $3}')"
go_version_at_least_1_24 "$go_version" || die "AmneziaWG 2.0 Go bridge requires Go 1.24 or newer; found $("$go_bin_dir/go" version)"

require_command xcodebuild
require_command rsync
require_command ditto
require_command codesign

mkdir -p "$tmp_root" "$go_cache" "$go_mod_cache"

if [[ "$clean" -eq 1 ]]; then
    rm -rf "$source_copy" "$derived_data"
fi

rsync -a --delete \
    --exclude '/.git/' \
    --exclude '/DerivedData/' \
    --exclude '/build/' \
    --exclude 'xcuserdata/' \
    --exclude '*.xcuserstate' \
    "$project_root/" "$source_copy/"

developer_xcconfig="$source_copy/Sources/WireGuardApp/Config/Developer.xcconfig"
if [[ ! -f "$developer_xcconfig" ]]; then
    mkdir -p "$(dirname "$developer_xcconfig")"
    {
        echo "// Generated by scripts/build-macos.sh for local builds."
        echo "DEVELOPMENT_TEAM = ${DEVELOPMENT_TEAM:-}"
        echo "APP_ID_IOS = ${APP_ID_IOS:-com.lexor.awg.ios}"
        echo "APP_ID_MACOS = ${APP_ID_MACOS:-com.lexor.awg.macos}"
    } > "$developer_xcconfig"
fi

xcode_settings=()
[[ -n "${DEVELOPMENT_TEAM:-}" ]] && xcode_settings+=("DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM")
[[ -n "${APP_ID_MACOS:-}" ]] && xcode_settings+=("APP_ID_MACOS=$APP_ID_MACOS")
[[ -n "${APP_ID_IOS:-}" ]] && xcode_settings+=("APP_ID_IOS=$APP_ID_IOS")

provisioning_args=()
signing_args=()
if [[ "$signing_mode" == "signed" ]]; then
    team_value="${DEVELOPMENT_TEAM:-$(read_xcconfig_value DEVELOPMENT_TEAM "$developer_xcconfig")}"
    if [[ -z "$team_value" || "$team_value" == "<team_id>" ]]; then
        die "signed mode requires DEVELOPMENT_TEAM in Developer.xcconfig or the environment"
    fi
    if [[ "${ALLOW_PROVISIONING_UPDATES:-0}" == "1" ]]; then
        provisioning_args+=("-allowProvisioningUpdates")
    fi
else
    signing_args+=("CODE_SIGNING_ALLOWED=NO" "CODE_SIGNING_REQUIRED=NO" "CODE_SIGN_IDENTITY=")
fi

echo "Project: $project_root"
echo "Temp source: $source_copy"
echo "DerivedData: $derived_data"
echo "Configuration: $configuration"
echo "Signing: $signing_mode"
echo "SwiftLint skipped: $skip_swiftlint"
echo "Go: $("$go_bin_dir/go" version)"

xcodebuild_args=(
    -project WireGuard.xcodeproj
    -scheme "$scheme"
    -configuration "$configuration"
    -destination "$destination"
    -derivedDataPath "$derived_data"
)
if ((${#provisioning_args[@]})); then
    xcodebuild_args+=("${provisioning_args[@]}")
fi
if ((${#signing_args[@]})); then
    xcodebuild_args+=("${signing_args[@]}")
fi
if ((${#xcode_settings[@]})); then
    xcodebuild_args+=("${xcode_settings[@]}")
fi
xcodebuild_args+=(build)

(
    cd "$source_copy"
    env \
        "PATH=$go_bin_dir:$PATH" \
        "GOCACHE=$go_cache" \
        "GOMODCACHE=$go_mod_cache" \
        "SKIP_SWIFTLINT=$skip_swiftlint" \
        xcodebuild "${xcodebuild_args[@]}"
)

app_path="$derived_data/Build/Products/$configuration/WireGuard.app"
[[ -d "$app_path" ]] || die "expected app not found: $app_path"

if [[ "$signing_mode" == "unsigned" ]]; then
    echo "Applying local ad-hoc signature"
    codesign --force --deep --sign - --timestamp=none "$app_path"
fi

codesign --verify --deep --strict --verbose=2 "$app_path"

if [[ "$create_archive" -eq 1 ]]; then
    stamp="${AWG_BUILD_STAMP:-$(date +%Y%m%d-%H%M)}"
    configuration_slug="$(printf '%s' "$configuration" | tr '[:upper:]' '[:lower:]')"
    signing_slug="$signing_mode"
    [[ "$signing_mode" == "unsigned" ]] && signing_slug="ad-hoc"
    output_dir="$output_root/macos-$configuration_slug-$stamp"
    zip_path="$output_dir/WireGuard-macos-$configuration_slug-$signing_slug-$stamp.zip"

    mkdir -p "$output_dir"
    ditto -c -k --sequesterRsrc --keepParent "$app_path" "$zip_path"

    echo "Archive: $zip_path"
fi

echo "App: $app_path"
